### ISSUE TITLE
The inconsistent results of your modified 3D U-Net and mine

### ISSUE THREAD

**Issue by peter850706** [baumgach/acdc_segmenter#5]
Hello,
I try to reproduce the result of the modified 3D U-Net model as described in [your paper](https://arxiv.org/pdf/1709.04496.pdf), and I use the default setting of your code except the loss function (use Dice loss), but I got pretty worse Dice score than yours ([summary_report.txt.txt](https://github.com/baumgach/acdc_segmenter/files/2714491/summary_report.txt.txt)). Could you share your training details or tricks about training this 3D model? Thanks a lot!

**Comment by baumgach** [comment]
There was indeed a bug in the 3D evaluation function. I am surprised you were able to get any Dice scores because it was predicting everything as zero. Anyway, it is now fixed.
